### ISSUE TITLE
pypi release?

### ISSUE THREAD

**Issue by ipfans** [Linusp/python-inoreader#1]
提交个版本到pypi上？可以方便使用

**Comment by Linusp** [comment]
抱歉过了这么久才看到……

有计划放到 pypi，但是目前还在很早期的阶段，基本就是自用。如果在使用的话有没有意见可以提供呢？

**Comment by Linusp** [comment]
已经制定了计划：https://github.com/Linusp/python-inoreader/projects/1

**Comment by Linusp** [comment]
已发布到 pypi，以后 `pip install python-inoreader` 即可安装
