### ISSUE TITLE
Bug causing infinite loop while retrieving un-read articles

### ISSUE THREAD

**Issue by ivan98** [Linusp/python-inoreader#12]
https://github.com/Linusp/python-inoreader/blob/68dd1b3eee167bc1ad6e3c34e20a5b8a933e0938/inoreader/client.py#L198
`continuation` is a Boolean.

https://github.com/Linusp/python-inoreader/blob/68dd1b3eee167bc1ad6e3c34e20a5b8a933e0938/inoreader/client.py#L200
This line is a bug. It should be
` params['c'] = response.get('continuation')`

**Comment by Linusp** [comment]
Thank you for reporting this! I'll fix it this week.

**Comment by Linusp** [comment]
Hi @ivan98 , this issue is fixed in #13 , so I'll close this issue now. Thanks again!
